version: "3"

networks:
  publicnet:
    external: true
  internal:
    external: false

volumes:
  nextcloud:
  mdb:

services:
  traefik:
    image: "traefik:${TRAEFIK_TAG}"
    command: --docker
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
      - "traefik.port=8080"
    networks:
      - publicnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
    restart: always


  giteadb:
    image: "postgres:${GITEA_DB_TAG}"
    restart: always
    env_file:
      - giteadb.env
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - ./postgres:/var/lib/postgresql/data

  gitea:
    image: "gitea/gitea:${GITEA_TAG}"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /opt/docker_compose/backup:/backup
    ports:
      - "3000"
      - "22"
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=gitea"
      - "traefik.frontend.rule=Host:git.${DOMAIN}"
      - "traefik.docker.network=publicnet"
      - "traefik.port=3000"
    networks:
      - internal
      - publicnet
    depends_on:
      - giteadb
      - traefik


  nextclouddb:
    image: "mariadb:${NEXTCLOUD_DB_TAG}"
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - nextclouddb.env
    ports:
      - 3306:3306
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - mdb:/var/lib/mysql

  nextcloud:
    build: Dockerfile_nextcloud
    restart: always
    ports:
      - 8080:80
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:cloud.${DOMAIN}"
      - "traefik.docker.network=publicnet"
      - "traefik.port=80"
    depends_on:
      - nextclouddb
      - traefik
    volumes:
      - nextcloud:/var/www/html
    networks:
      - publicnet
      - internal
