version: "3"

networks:
  publicnet:
    external: true
  internal:
    external: false

volumes:
  nextcloud:
  mdb:

services:
  traefik:
    image: "traefik:v2.8.3"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=auth-traefik"
      - "traefik.http.middlewares.auth-traefik.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_USER_TOKEN}"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le-resolver"
    networks:
      - publicnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    container_name: traefik


  giteadb:
    image: "postgres:14.5"
    restart: always
    env_file:
      - giteadb.env
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - ./postgres:/var/lib/postgresql/data

  gitea:
    image: "gitea/gitea:1.17.1"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /opt/docker_compose/backup:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000"
      - "22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=le-resolver"
      - "traefik.http.routers.gitea.service=gitea-web-svc"
      - "traefik.http.services.gitea-web-svc.loadbalancer.server.port=3000"
      - "traefik.docker.network=publicnet"
    networks:
      - internal
      - publicnet
    depends_on:
      - giteadb
      - traefik

#  new-giteadb:
#    image: "postgres:14.5"
#    restart: always
#    env_file:
#      - giteadb.env
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - internal
#    volumes:
#      - ./new-postgres:/var/lib/postgresql/data
#
#  new-gitea:
#    image: "gitea/gitea:1.17.1"
#    environment:
#      - USER_UID=1000
#      - USER_GID=1000
#      - GITEA__database__DB_TYPE=postgres
#      - "GITEA__database__HOST=${GITEA_DB_HOST}:5432"
#      - "GITEA__database__NAME=${GITEA_DB_NAME}"
#      - "GITEA__database__USER=${GITEA_DB_USER}"
#      - "GITEA__database__PASSWD=${GITEA_DB_PASSWORD}"
#    restart: always
#    volumes:
#      - ./new-gitea:/data
#      - /opt/docker_compose/new-backup:/backup
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "3000"
#      - "22"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.new-gitea.rule=Host(`new-git.${DOMAIN}`)"
#      - "traefik.http.routers.new-gitea.entrypoints=websecure"
#      - "traefik.http.routers.new-gitea.tls=true"
#      - "traefik.http.routers.new-gitea.tls.certresolver=le-resolver"
#      - "traefik.http.routers.new-gitea.service=new-gitea-web-svc"
#      - "traefik.http.services.new-gitea-web-svc.loadbalancer.server.port=3000"
#      - "traefik.docker.network=publicnet"
#    networks:
#      - internal
#      - publicnet
#    depends_on:
#      - new-giteadb
#      - traefik


  nextclouddb:
    image: "mariadb:10.4.12-bionic"
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - nextclouddb.env
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - mdb:/var/lib/mysql

  nextcloud:
    build: Dockerfile_nextcloud
    restart: always
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=le-resolver"
      - "traefik.docker.network=publicnet"
    depends_on:
      - nextclouddb
      - traefik
    volumes:
      - nextcloud:/var/www/html
    networks:
      - publicnet
      - internal
